apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  labels:
    app: keycloak-svc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak-master
  type: NodePort