spring:
  data:
    mongodb:
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
  http:
    log-request-details: true
---

app:
  url:
    local: http://localhost:8080
    user: http://localhost:8082

  history:
    defaultPage: 0
    pageSize: 5
  cors:
    allowedOrigins: