
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    mongodb:
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
  http:
    log-request-details: true
---

app:
  url:
    local: http://localhost:8080
    user: http://localhost:8081

  history:
    defaultPage: 0
    pageSize: 5
  cors:
    allowedOrigins: