
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://34.105.178.183.xip.io/auth/realms/FirstApp
  data:
    mongodb:
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
  http:
    log-request-details: true
---

app:
  url:
    local: http://localhost:8080
    user: http://localhost:8081

  history:
    defaultPage: 0
    pageSize: 5
  cors:
    allowedOrigins: