apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  rules:
    - host: tourdeshot.teamg.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
          - path: /api/local
            backend:
              serviceName: core
              servicePort: 8080
          - path: /api/product-category
            backend:
              serviceName: core
              servicePort: 8080
          - path: /api/menu
            backend:
              serviceName: core
              servicePort: 8080
          - path: /api/userhistory
            backend:
              serviceName: history
              servicePort: 8080
          - path: /api/summary
            backend:
              serviceName: history
              servicePort: 8080
          - path: /auth
            backend:
              serviceName: keycloak
              servicePort: 8080