version: '3.7'

services:
  proxy:
    image: nginx:1.17.9-alpine
    container_name: dev_reverse_proxy
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - core
      - user
    ports:
      - 80:80
    networks:
      - core_net

  mongo_core:
    image: mongo:4.0
    container_name: dev_core_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - core_net

  core:
    image: mateusz43211/tourdeshot:core_latest
    container_name: dev_core
    restart: always
    ports:
      - 9090:9090
    environment:
      SERVER_PORT: 9090
      SPRING_DATA_MONGODB_HOST: mongo_core
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mongo_core
    networks:
      - core_net

  user:
    image: mateusz43211/tourdeshot:user_latest
    container_name: dev_user
    restart: always
    ports:
      - 9091:9091
    environment:
      SERVER_PORT: 9091
    networks:
      - core_net


networks:
  core_net: