spring:
  data:
    mongodb:
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
---

app:
  local:
    defaultPage: 0
    pageSize: 5
  localizationFilter:
    latitude: 52.236216
    longitude: 21.012059
    maxDistance: 1.0
  categoryFilter:
    minPrice: 0.0
    maxPrice: 1000000.0

  cors:
    allowedOrigins:
