spring:
  data:
    mongodb:
      port: 27017
      username: mongoadmin
      password: secret
      authentication-database: admin
---

app:
  local:
    defaultPage: 0
    pageSize: 5
  cors:
    allowedOrigins: