apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-master-deployment
  labels:
    app: history-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-master
  template:
    metadata:
      labels:
        app: history-master
    spec:
      containers:
        - name: history-master
          image: mateusz43211/tourdeshot:userhistory_1.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-history
            - name: SPRING_DATA_MONGODB_PORT
              value: '27017'
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-history-config
                  key: MONGODB_TDS_DBNAME
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-history
                  key: db-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-history
                  key: db-password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-history-config
                  key: MONGODB_TDS_DBNAME
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /api
            - name: APP_CORS_ALLOWEDORIGINS_0
              valueFrom:
                configMapKeyRef:
                  name: history-config
                  key: APP_CORS_ALLOWEDORIGINS_0
            - name: APP_CORS_ALLOWEDORIGINS_1
              valueFrom:
                configMapKeyRef:
                  name: history-config
                  key: APP_CORS_ALLOWEDORIGINS_1
            - name: APP_URL_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: history-config
                  key: APP_URL_LOCAL
#            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
#              valueFrom:
#                secretKeyRef:
#                  name: history-secret-conf
#                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI