apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-history-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo-history
  name: mongo-history
spec:
  serviceName: mongo-history
  replicas: 1
  selector:
    matchLabels:
      app: mongo-history
  template:
    metadata:
      labels:
        app: mongo-history
    spec:
      containers:
        - name: mongo-history
          image: mongo:4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-history-storage
              mountPath: /data/db
            - name: mongo-history-entrypoint-volume
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MONGODB_TDS_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-history-config
                  key: MONGODB_TDS_DBNAME
            - name: MONGODB_TDS_ROLE
              valueFrom:
                configMapKeyRef:
                  name: mongo-history-config
                  key: MONGODB_TDS_ROLE
            - name: MONGODB_TDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-history
                  key: db-username
            - name: MONGODB_TDS_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-history
                  key: db-password
          resources:
            limits:
              memory: "256Mi"
              cpu: "50m"
      volumes:
        - name: mongo-history-storage
          persistentVolumeClaim:
            claimName: mongo-history-pvc
        - name: mongo-history-entrypoint-volume
          configMap:
            name: mongo-history-entrypoint

