apiVersion: v1
kind: Service
metadata:
  name: mongo-history
  labels:
    app: mongo-history
spec:
  type: ClusterIP
  selector:
    app: mongo-history
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017