DROP SCHEMA IF EXISTS `rso`;
CREATE SCHEMA IF NOT EXISTS `rso`;
USE rso;

CREATE TABLE IF NOT EXISTS client
(
    id    BIGINT(20)  NOT NULL AUTO_INCREMENT,
    login VARCHAR(25) NOT NULL,
    PRIMARY KEY (id)
);