apiVersion: v1
kind: Service
metadata:
  name: mongo-core
  labels:
    app: mongo-core
spec:
  type: ClusterIP
  selector:
    app: mongo-core
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017