apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-master-deployment
  labels:
    app: core-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-master
  template:
    metadata:
      labels:
        app: core-master
    spec:
      containers:
        - name: core-master
          image: mateusz43211/tourdeshot:core_1.13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-core
            - name: SPRING_DATA_MONGODB_PORT
              value: '27017'
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-core-config
                  key: MONGODB_TDS_DBNAME
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-core
                  key: db-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-core
                  key: db-password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-core-config
                  key: MONGODB_TDS_DBNAME
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: APP_CORS_ALLOWEDORIGINS_0
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: APP_CORS_ALLOWEDORIGINS_0
            - name: APP_CORS_ALLOWEDORIGINS_1
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: APP_CORS_ALLOWEDORIGINS_1
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /api
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: core-secret-conf
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI